.\" Copyright (C) 2007 Sven Arvidsson <sa@whiz.se>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH gnome-mines 6 "2007\-06\-09" "GNOME"
.SH NAME
Mines \- The popular logic puzzle minesweeper
.SH SYNOPSIS
.B gnome-mines
.RI [ OPTION... ]
.SH DESCRIPTION
.B gnome-mines
is a puzzle game where you locate mines floating in an ocean using
only your brain and a little bit of luck.
.SH OPTIONS
.TP
.B \-v, \-\-version
Print release version and exit
.PP
.B \-\-small
.br
.B \-\-medium
.br
.B \-\-big
.RS 7
Start the game with a small (8 by 8), medium (16 by 16) or big (30 by 16) board.
If more than one of these options is given, the biggest size is selected.
.RE
.P
This program also accepts the standard GNOME and GTK options.
.SH AUTHORS
.B gnome-mines
was written by Szekeres Istvan and others.
.P
This manual page was written by Sven Arvidsson <sa@whiz.se>,
for the Debian project (but may be used by others).
.SH SEE ALSO
.BR "gtk-options" (7),
.BR "gnome-options" (7)
.P
The online documentation available through the program's
.I Help
menu.
