name: gnome-mines
version: git
summary: Clear hidden mines from a minefield
description: |
  GNOME Mines is a puzzle game where you search for hidden mines. Flag the
  spaces with mines as quickly as possible to make the board a safer place. You
  win the game when you’ve flagged every mine on the board. Be careful not to
  trigger one, or the game is over!

  You can select the size of the field you want to play on at the start of the
  game. If you get stuck, you can ask for a hint: there’s a time penalty, but
  that’s better than hitting a mine!

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

# Launchpad doesn't recognize these fields yet
passthrough:
  license: GPL-3.0+
  title: GNOME Mines

slots:
  # for GtkApplication registration
  gnome-mines:
    interface: dbus
    bus: session
    name: org.gnome.Mines

apps:
  gnome-mines:
    command: usr/bin/gnome-mines
    extensions: [gnome-3-28]
    plugs:
      - gsettings
    desktop: usr/share/applications/org.gnome.Mines.desktop

parts:
  gnome-mines:
    source: .
    source-type: git
    override-build: |
      sed -i.bak -e 's|=org.gnome.Mines$|=${SNAP}/meta/gui/org.gnome.Mines.svg|g' data/org.gnome.Mines.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/org.gnome.Mines.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../install/snap/gnome-mines/current/usr/share/applications/org.gnome.Mines.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters: [--prefix=/snap/gnome-mines/current/usr]
    organize:
      snap/gnome-mines/current/usr: usr
    build-packages:
      - gettext
      - itstool
      - libglib2.0-dev
      - libgnome-games-support-1-dev
      - libgtk-3-dev
      - librsvg2-dev
      - libxml2-utils
      - valac
  libraries:
    plugin: nil
    stage-packages:
      - libgnome-games-support-1-3
      - libgee-0.8-2
    prime:
      - "usr/lib/*/libgnome-games-support-1.so.*"
      - "usr/lib/x86_64-linux-gnu/libgee-0.8.so.*"
